# Prism Service Onboarding Specification
# Version: 1.0

# Comments:
# - Ensure all mandatory fields are completed for successful onboarding.
# - Specify environment-specific details clearly for Splunk and New Relic configurations.
# - Use environment-specific webhook URLs for triggering alert actions in each monitoring source.

version: "1.0"

service:
  # Name of the service (Mandatory)
  name: "Petclinic Service"

  # Brief description of the service's purpose (Mandatory)
  description: "This is a demo service for onboarding purposes."

  owner:
    # Team responsible for the service (Mandatory)
    team: "prism@adobe.com"

    # Primary contact email for the service team (Mandatory)
    contact_email: "ishtiyaq@adobe.com"

# List of environments where the service is deployed (Mandatory)
environments:
  -
    # Name of the environment (e.g., "production", "staging") (Mandatory)
    name: "stage"
    # URL of the service in this environment (Optional)
    url: "https://demo-service-stage.adobe.com"

    monitoring:
      new_relic:
        # Name of the New Relic application for this environment (Mandatory)
        app_name: "demo-dev-va6"
        # Webhook URL for New Relic alert actions in this environment (Mandatory)
        nexus_webhook_url: "https://nexus-ext.goc.adobe.net/api/notify/newrelic/v2?ruleset=cc-cross-product-services&rules=prism"
# End of Prism Service Onboarding Specification
